name: tukutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0        # Firebaseのコア初期化用 ^2.10.0 から ^2.32.0に変更
  firebase_auth: ^5.5.3         # 認証用（ログインなど） ^4.4.0 から 4.16.0に変更
  cloud_firestore: ^5.6.7       # Firestore用（データベース）
  google_sign_in: ^6.3.0        # Googleログイン用 ^6.0.0 から 6.2.0に変更
  http: ^1.0.0                  # Cloudinary用（画像アップロードに使うこともある）

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
