name: tukutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1        
  cloud_firestore: ^4.5.0       # Firestore用（データベース）
  http: ^1.0.0                  # Cloudinary用（画像アップロードに使うこともある）

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
