// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3s8xHONDAd27PFcnrlOuV9E2ktzQig3U',
    appId: '1:70406727070:web:ab3519d84b87a18a8b228f',
    messagingSenderId: '70406727070',
    projectId: 'tukutter-8008e',
    authDomain: 'tukutter-8008e.firebaseapp.com',
    storageBucket: 'tukutter-8008e.firebasestorage.app',
    measurementId: 'G-L03V68XXY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo1HyBWA_S0eW3QW6u_RynPhP_rVIsspk',
    appId: '1:70406727070:android:a48961e741f084a38b228f',
    messagingSenderId: '70406727070',
    projectId: 'tukutter-8008e',
    storageBucket: 'tukutter-8008e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGoF9VDRChH5X0VIrQ9nL8vCWiEdeoHM',
    appId: '1:70406727070:ios:cb14f609a0e7e53a8b228f',
    messagingSenderId: '70406727070',
    projectId: 'tukutter-8008e',
    storageBucket: 'tukutter-8008e.firebasestorage.app',
    iosClientId: '70406727070-kp8o6gb04s70h0pk17cn30cvqn4mc74g.apps.googleusercontent.com',
    iosBundleId: 'com.hack1.tukutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSGoF9VDRChH5X0VIrQ9nL8vCWiEdeoHM',
    appId: '1:70406727070:ios:52fcf69aea5a0e378b228f',
    messagingSenderId: '70406727070',
    projectId: 'tukutter-8008e',
    storageBucket: 'tukutter-8008e.firebasestorage.app',
    iosClientId: '70406727070-5ek4omtu5lgr4387c133uco4ll82q8ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.tukutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3s8xHONDAd27PFcnrlOuV9E2ktzQig3U',
    appId: '1:70406727070:web:cd98823f0e32f13f8b228f',
    messagingSenderId: '70406727070',
    projectId: 'tukutter-8008e',
    authDomain: 'tukutter-8008e.firebaseapp.com',
    storageBucket: 'tukutter-8008e.firebasestorage.app',
    measurementId: 'G-FB605E9QL8',
  );
}
